In [1]:
import pandas as pd

import seaborn as sns

In [2]:
df = pd.read_csv('Churn_Modelling.csv')
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [4]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
#2. Distinguish the feature and target set and divide the data set into training and test sets.
X = df.drop(columns=['RowNumber', 'CustomerId', 'Surname', 'Exited'])  # Dropping non-predictive columns
y = df['Exited']

In [6]:
#Encode Categorical Features
#Convert categorical features like Geography and Gender into numerical values using one-hot encoding.
print(X)

      CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1
1             608     Spain  Female   41       1   83807.86              1
2             502    France  Female   42       8  159660.80              3
3             699    France  Female   39       1       0.00              2
4             850     Spain  Female   43       2  125510.82              1
...           ...       ...     ...  ...     ...        ...            ...
9995          771    France    Male   39       5       0.00              2
9996          516    France    Male   35      10   57369.61              1
9997          709    France  Female   36       7       0.00              1
9998          772   Germany    Male   42       3   75075.31              2
9999          792    France  Female   28       4  130142.79              1

      HasCrCard  IsActiveMember  EstimatedSalary
0             1               1        101348.88
1             0               1        112542.58
2             1               0        113931.57
3             0               0         93826.63
4             1               1         79084.10
...         ...             ...              ...
9995          1               0         96270.64
9996          1               1        101699.77
9997          0               1         42085.58
9998          1               0         92888.52
9999          1               0         38190.78

[10000 rows x 10 columns]

In [7]:
print(y)

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [8]:
#We need to encode categorical variables such as geography and gender
from sklearn.preprocessing import LabelEncoder
X_column_transformer = LabelEncoder()

#Lets Encode Geography now
X.iloc[:, 1] = X_column_transformer.fit_transform(X.iloc[:, 1])

In [9]:
#Lets Encode gender now
X.iloc[:, 2] = X_column_transformer.fit_transform(X.iloc[:, 2])

In [10]:
print(X)

      CreditScore Geography Gender  Age  Tenure    Balance  NumOfProducts  \
0             619         0      0   42       2       0.00              1
1             608         2      0   41       1   83807.86              1
2             502         0      0   42       8  159660.80              3
3             699         0      0   39       1       0.00              2
4             850         2      0   43       2  125510.82              1
...           ...       ...    ...  ...     ...        ...            ...
9995          771         0      1   39       5       0.00              2
9996          516         0      1   35      10   57369.61              1
9997          709         0      0   36       7       0.00              1
9998          772         1      1   42       3   75075.31              2
9999          792         0      0   28       4  130142.79              1

      HasCrCard  IsActiveMember  EstimatedSalary
0             1               1        101348.88
1             0               1        112542.58
2             1               0        113931.57
3             0               0         93826.63
4             1               1         79084.10
...         ...             ...              ...
9995          1               0         96270.64
9996          1               1        101699.77
9997          0               1         42085.58
9998          1               0         92888.52
9999          1               0         38190.78

[10000 rows x 10 columns]

In [11]:
#Split the Dataset into Training and Test Sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input

# Initialize the neural network
model = Sequential()

# Input layer and first hidden layer
model.add(Input(shape=(10,)))
model.add(Dense(units=64, activation='relu'))
model.add(Dropout(0.3))

# Second hidden layer
model.add(Dense(units=32, activation='relu'))
model.add(Dropout(0.2))

# Output layer
model.add(Dense(units=1, activation='sigmoid'))  # Sigmoid for binary classification

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [15]:
#Train the Model
#Fit the model on the training data.
history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7989 - loss: 0.5062 - val_accuracy: 0.8138 - val_loss: 0.4270
Epoch 2/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8040 - loss: 0.4465 - val_accuracy: 0.8256 - val_loss: 0.4169
Epoch 3/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8133 - loss: 0.4345 - val_accuracy: 0.8369 - val_loss: 0.4011
Epoch 4/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.8187 - loss: 0.4258 - val_accuracy: 0.8462 - val_loss: 0.3854
Epoch 5/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - accuracy: 0.8266 - loss: 0.4014 - val_accuracy: 0.8456 - val_loss: 0.3755
Epoch 6/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.8323 - loss: 0.3976 - val_accuracy: 0.8500 - val_loss: 0.3650
Epoch 7/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - accuracy: 0.8412 - loss: 0.3850 - val_accuracy: 0.8506 - val_loss: 0.3589
Epoch 8/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.8520 - loss: 0.3689 - val_accuracy: 0.8556 - val_loss: 0.3551
Epoch 9/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.8512 - loss: 0.3746 - val_accuracy: 0.8500 - val_loss: 0.3534
Epoch 10/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.8535 - loss: 0.3570 - val_accuracy: 0.8525 - val_loss: 0.3502
Epoch 11/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step - accuracy: 0.8476 - loss: 0.3668 - val_accuracy: 0.8556 - val_loss: 0.3481
Epoch 12/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8491 - loss: 0.3721 - val_accuracy: 0.8506 - val_loss: 0.3494
Epoch 13/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.8424 - loss: 0.3765 - val_accuracy: 0.8556 - val_loss: 0.3472
Epoch 14/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.8485 - loss: 0.3695 - val_accuracy: 0.8537 - val_loss: 0.3462
Epoch 15/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.8512 - loss: 0.3504 - val_accuracy: 0.8531 - val_loss: 0.3460
Epoch 16/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.8532 - loss: 0.3569 - val_accuracy: 0.8537 - val_loss: 0.3465
Epoch 17/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.8530 - loss: 0.3667 - val_accuracy: 0.8544 - val_loss: 0.3450
Epoch 18/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8612 - loss: 0.3426 - val_accuracy: 0.8544 - val_loss: 0.3455
Epoch 19/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - accuracy: 0.8530 - loss: 0.3531 - val_accuracy: 0.8550 - val_loss: 0.3452
Epoch 20/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1000us/step - accuracy: 0.8590 - loss: 0.3473 - val_accuracy: 0.8550 - val_loss: 0.3435
Epoch 21/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - accuracy: 0.8546 - loss: 0.3545 - val_accuracy: 0.8575 - val_loss: 0.3452
Epoch 22/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 999us/step - accuracy: 0.8598 - loss: 0.3554 - val_accuracy: 0.8581 - val_loss: 0.3424
Epoch 23/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.8576 - loss: 0.3502 - val_accuracy: 0.8569 - val_loss: 0.3425
Epoch 24/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 979us/step - accuracy: 0.8664 - loss: 0.3361 - val_accuracy: 0.8562 - val_loss: 0.3426
Epoch 25/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.8595 - loss: 0.3521 - val_accuracy: 0.8562 - val_loss: 0.3434
Epoch 26/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.8521 - loss: 0.3561 - val_accuracy: 0.8569 - val_loss: 0.3429
Epoch 27/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - accuracy: 0.8616 - loss: 0.3514 - val_accuracy: 0.8575 - val_loss: 0.3408
Epoch 28/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - accuracy: 0.8557 - loss: 0.3505 - val_accuracy: 0.8569 - val_loss: 0.3423
Epoch 29/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8622 - loss: 0.3398 - val_accuracy: 0.8544 - val_loss: 0.3436
Epoch 30/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8552 - loss: 0.3472 - val_accuracy: 0.8544 - val_loss: 0.3427
Epoch 31/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.8629 - loss: 0.3364 - val_accuracy: 0.8556 - val_loss: 0.3429
Epoch 32/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 979us/step - accuracy: 0.8583 - loss: 0.3418 - val_accuracy: 0.8575 - val_loss: 0.3416
Epoch 33/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.8574 - loss: 0.3409 - val_accuracy: 0.8544 - val_loss: 0.3411
Epoch 34/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.8538 - loss: 0.3386 - val_accuracy: 0.8562 - val_loss: 0.3419
Epoch 35/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.8655 - loss: 0.3310 - val_accuracy: 0.8575 - val_loss: 0.3419
Epoch 36/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - accuracy: 0.8647 - loss: 0.3382 - val_accuracy: 0.8581 - val_loss: 0.3449
Epoch 37/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.8573 - loss: 0.3446 - val_accuracy: 0.8587 - val_loss: 0.3402
Epoch 38/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8563 - loss: 0.3477 - val_accuracy: 0.8581 - val_loss: 0.3401
Epoch 39/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8615 - loss: 0.3418 - val_accuracy: 0.8562 - val_loss: 0.3408
Epoch 40/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8672 - loss: 0.3294 - val_accuracy: 0.8575 - val_loss: 0.3413
Epoch 41/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 994us/step - accuracy: 0.8588 - loss: 0.3460 - val_accuracy: 0.8581 - val_loss: 0.3432
Epoch 42/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.8620 - loss: 0.3291 - val_accuracy: 0.8594 - val_loss: 0.3429
Epoch 43/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8673 - loss: 0.3308 - val_accuracy: 0.8562 - val_loss: 0.3428
Epoch 44/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8603 - loss: 0.3384 - val_accuracy: 0.8600 - val_loss: 0.3414
Epoch 45/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 979us/step - accuracy: 0.8652 - loss: 0.3276 - val_accuracy: 0.8587 - val_loss: 0.3426
Epoch 46/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.8689 - loss: 0.3326 - val_accuracy: 0.8594 - val_loss: 0.3417
Epoch 47/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - accuracy: 0.8645 - loss: 0.3326 - val_accuracy: 0.8594 - val_loss: 0.3428
Epoch 48/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - accuracy: 0.8625 - loss: 0.3398 - val_accuracy: 0.8575 - val_loss: 0.3428
Epoch 49/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8664 - loss: 0.3314 - val_accuracy: 0.8581 - val_loss: 0.3417
Epoch 50/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - accuracy: 0.8727 - loss: 0.3244 - val_accuracy: 0.8569 - val_loss: 0.3415

In [16]:
# Evaluate the Model
#After training, evaluate the model on the test set.

from sklearn.metrics import accuracy_score, confusion_matrix

# # Predictions and evaluation
y_pred = (model.predict(X_test) > 0.5).astype("int32")

# # Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# # Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
Accuracy: 0.8635
Confusion Matrix:
 [[1549   58]
 [ 215  178]]